services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: campos_daguer_emilio
      MYSQL_USER: app_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_password
    ports:
      - "3307:3306"
    volumes:
      - ./config/mycnf.cnf:/etc/mysql/conf.d/mycnf.cnf

secrets:
  mysql_root_password:
    file: ./secrets/root_pwd.txt
  mysql_password:
    file: ./secrets/app_pwd.txt